name: CI/CD Pipeline

on:
  push:
    branches: [main, develop] # chạy khi push vào main hoặc develop
  pull_request:
    branches: [main]          # chạy CI khi mở PR vào main

jobs:
  # ===== Frontend CI & Deploy =====
  frontend:
    name: Frontend Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies & Build
  working-directory: client
  run: |
    npm ci
    npm run build
    # npm test -- --watchAll=false


      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: client
          prod: ${{ github.ref == 'refs/heads/main' }} # main = production, develop = preview

  # ===== Backend CI =====
  backend:
    name: Backend Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      #- name: Run Backend Tests
      # run: npm test
