name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend Install & Deploy (Render)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ./server/package-lock.json
      - name: Install backend dependencies
        working-directory: ./server
        run: npm ci
      - name: Trigger Render deploy on main
        if: github.ref == 'refs/heads/main'
        run: curl -fsS -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"

  frontend:
    name: Frontend Build & Deploy (Vercel)
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json
      - name: Install dependencies & Build
        working-directory: ./client
        run: |
          npm ci --no-audit --no-fund
          CI=false npm run build

      - name: Deploy to Vercel (preview on non-main)
        if: github.ref != 'refs/heads/main'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-project-path: ./client

      - name: Deploy to Vercel (production on main)
        if: github.ref == 'refs/heads/main'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          vercel-project-path: ./client
